version: "3.2"

services:
    frontend:
        build: frontend
        ports:
            - 20080:80
        volumes:
            # Re-use local composer cache via host-volume
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            # Mount source-code for development
            - ./:/app
        networks:
          - devmall-networks

    backend:
        build: admin
        ports:
            - 21080:80
        volumes:
            # Re-use local composer cache via host-volume
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            # Mount source-code for development
            - ./:/app
        networks:
          - devmall-networks

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=verysecret
            - MYSQL_DATABASE=devmall_dev
            - MYSQL_USER=devmall_user
            - MYSQL_PASSWORD=secret
        volumes:
          - "devmall-db:/var/lib/mysql"
        networks:
          - devmall-networks

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8888:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - mysql
        networks:
          - devmall-networks
    #pgsql:
    #  image: postgres:9.5
    #  environment:
    #    - POSTGRES_DB=yii2advanced
    #    - POSTGRES_USER=yii2advanced
    #    - POSTGRES_PASSWORD=secret

volumes:
    devmall-db:

networks:
    devmall-networks:
        driver: bridge
